# Site settings
title: Pauls Website
email: pnieves1234@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple and clean Jekyll site built for GitHub Pages.
baseurl: "/Pauls-Website" # For user/organization sites, leave it empty. For project sites, set it to /my-project.
url: "https://paulnation.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer # You can change this to any other theme or remove it to use the default theme

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Social Media Links
twitter_username: PaulNation45
github_username: paulnation

# Google Analytics
google_analytics: UA-XXXXXX-X # Replace with your Google Analytics tracking ID

# Exclude files from being processed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalinks
permalink: /:year/:month/:day/:title/

# Language
locale: en

# Custom Collections (if needed)
# collections:
#   my_collection:
#     output: true